[package]
name = "motif-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
motif-core.workspace = true
rtrb.workspace = true
thiserror.workspace = true
wmidi.workspace = true
