[package]
name = "motif"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
motif-ui.workspace = true
motif-core.workspace = true
motif-engine.workspace = true
motif-pulse.workspace = true
iced.workspace = true
rtrb.workspace = true
cpal.workspace = true
